---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kmcp-system
---
# Source: gitops-chart/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Project platform
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kagent
    - server: https://kubernetes.default.svc
      namespace: kmcp-system
    - server: https://kubernetes.default.svc
      namespace: test-app
  sourceRepos:
    - https://github.com/qasmi/smart-idp.git
    - ghcr.io/kagent-dev/kagent/helm
    - ghcr.io/kagent-dev/kmcp/helm
    - ghcr.io/stapr-idp
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: apiregistration.k8s.io
      kind: APIService
    - group: scheduling.k8s.io
      kind: PriorityClass
---
# Source: gitops-chart/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  description: Project security
  destinations:
  sourceRepos:
    - https://github.com/qasmi/smart-idp.git
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: apiregistration.k8s.io
      kind: APIService
---
# Source: gitops-chart/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: 0
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  revisionHistoryLimit: 
  source:
    repoURL: ghcr.io/kagent-dev/kagent/helm
    chart: kagent-crds
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
  ignoreDifferences: []
---
# Source: gitops-chart/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: 1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  revisionHistoryLimit: 
  source:
    repoURL: ghcr.io/kagent-dev/kagent/helm
    chart: kagent
    targetRevision: "0.6.15"
    helm:
      valueFiles:
        - team-platform/values/kagent.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
  ignoreDifferences: []
---
# Source: gitops-chart/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: 2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  revisionHistoryLimit: 
  source:
    repoURL: ghcr.io/kagent-dev/kmcp/helm
    chart: kmcp-crds
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: kmcp-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
  ignoreDifferences: []
---
# Source: gitops-chart/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: 3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  revisionHistoryLimit: 
  source:
    repoURL: ghcr.io/kagent-dev/kmcp/helm
    chart: kmcp
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: kmcp-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
  ignoreDifferences: []
---
# Source: gitops-chart/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: 4
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  revisionHistoryLimit: 
  source:
    repoURL: ghcr.io/stapr-idp
    chart: test-app
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
  ignoreDifferences: []
