---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kmcp-system
---
# Source: gitops-chart/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Project platform
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kagent
    - server: https://kubernetes.default.svc
      namespace: kmcp-system
  sourceRepos:
    - https://github.com/qasmi/smart-idp.git
    - ghcr.io/kagent-dev/kagent/helm
    - ghcr.io/kagent-dev/kmcp/helm
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: apiregistration.k8s.io
      kind: APIService
    - group: scheduling.k8s.io
      kind: PriorityClass
---
# Source: gitops-chart/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  description: Project security
  destinations:
  sourceRepos:
    - https://github.com/qasmi/smart-idp.git
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: apiregistration.k8s.io
      kind: APIService
