---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: user
  namespace: argocd
spec:
  description: User project
  destinations:
    - server: https://kubernetes.default.svc
      namespace: game-2048
  sourceRepos:
    - http://daocloud.github.io/dao-2048/
---
apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: game-2048
spec:
  hard:
    requests.cpu: "1"  
    requests.memory: "1Gi" 
    limits.cpu: "1"  
    limits.memory: "1Gi" 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argocd
spec:
  destination:
    namespace: game-2048
    server: https://kubernetes.default.svc
  project: user
  revisionHistoryLimit: 3
  sources:
  - chart: drupal
    helm:
      values: |
        drupalUsername: admin
        existingSecret: "drupal-app"

        externalDatabase:
          host: drupal-app-db-mariadb.drupal-app.svc.cluster.local
          port: 3306
          database: bitnami_drupal
          user: drupal
          existingSecret: "drupal-app-externaldb"

        nodeSelector:
          node/role: worker
        tolerations:
          - key: node/role
            value: worker
            operator: Equal
            effect: NoSchedule

        resources:
          limits:
            cpu: 2000m
            memory: 2000M
          requests:
            cpu: 2000m
            memory: 2000M
                
        pdb:
          minAvailable: 2

        mariadb:
          enabled: false
        networkPolicy:
          enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "21.0.0"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

