apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: game-2048
spec:
  hard:
    requests.cpu: "1"  
    requests.memory: "1Gi" 
    limits.cpu: "1"  
    limits.memory: "1Gi" 
    pods: "1"   
    services: "5"  
    persistentvolumeclaims: "4"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argocd
spec:
  destination:
    namespace: game-2048
    server: https://kubernetes.default.svc
  project: platform
  revisionHistoryLimit: 3
  sources:
  - chart: dao-2048
    helm:
      values: |
        replicaCount: 2

        resources: 
          limits:
            cpu: 1500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        nodeSelector:
          node-role: storage
        tolerations:
          - key: node-role
            value: storage
            operator: Equal
            effect: NoSchedule
      
        service:
          #type: LoadBalancer
          clusterIP: "172.18.250.0"

    repoURL: http://daocloud.github.io/dao-2048/
    targetRevision: "1.2.1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
