---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: platform
  revisionHistoryLimit: 5
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "1.17.*"
    helm:
      values: |
        nodeSelector:
          node.un.org/role: tooling
        
        tolerations:
          - key: node.un.org/role
            value: tooling
            operator: Equal
            effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions: