---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kubeconNA
---
# Source: gitops-chart/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubeconNA
  namespace: argocd
spec:
  description: Demo project
  sourceRepos:
    - https://github.com/qasmi/smart-idp.git
---
# Source: gitops-chart/templates/applicationSet.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal-app
  namespace: argocd
spec:
  destination:
    namespace: kubeconNA
    server: https://kubernetes.default.svc
  project: platform
  revisionHistoryLimit: 3
  sources:
  - chart: drupal
    helm:
      values: |
        drupalUsername: admin
        existingSecret: "drupal-app"

        externalDatabase:
          host: drupal-app-db-mariadb.drupal-app.svc.cluster.local
          port: 3306
          database: bitnami_drupal
          user: drupal
          existingSecret: "drupal-app-externaldb"

        nodeSelector:
          node.un.org/role: worker
        tolerations:
          - key: node.un.org/role
            value: worker
            operator: Equal
            effect: NoSchedule

        service:
          type: ClusterIP

        persistence:
          enabled: false

        image:
          debug: true

        mariadb:
          enabled: false

    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 21.0.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true