apiVersion: v1
stringData:
  GITHUB_PERSONAL_ACCESS_TOKEN: $GITHUB_PERSONAL_ACCESS_TOKEN
  GITHUB_TOOLSETS: "repos,issues,pull_requests,actions,code_security,experiments"
kind: Secret
metadata:
  name: github-mcp-secret
  namespace: kagent
type: Opaque
---
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-mcp-server
  namespace: kagent
spec:
  deployment:    
    args:
    - 'stdio'
    cmd: "/server/github-mcp-server"
    image: ghcr.io/github/github-mcp-server
    port: 3000
    secretRefs:
    - name: github-mcp-secret
  transportType: stdio
