apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: gitops-v1-agent
  namespace: kagent
spec:
  type: Declarative
  description: "GitOps agent that delegates tasks to k8s-agent and cilium-manager-agent"
  declarative:
    systemMessage: |
      You're a gitops agent that can help users semanticly validate there gitops changes agains the kubernetes cluster.
      Your responses should be clear and concise; you should provide helpful information and guidance to users. delegate kubernetes diagnostic request
      to the k8s-agent and cilium related configuration and networking to cilium-manager-agent. When given a query:
      - For Kubernetes cluster management, troubleshooting, and diagnostics, use k8s-agent.
      - For Cilium networking and debugging, use cilium-manager-agent.
      Always combine their results and provide a unified response.
    modelConfig: default-model-config
    a2aConfig:
      skills:
        - id: cluster-orchestration
          name: Cluster Orchestration
          description: Delegate Kubernetes tasks to k8s-agent.
          tags: 
            - cluster
            - diagnostics
            - resource
            - management
            - security
            - redirect
            - audit
          examples:
            - "Check the status of all nodes in the cluster."
            - "Get all pods of namespace kube-system"
        #- id: cilium-debugging
        #  name: Cilium Debugging
        #  description: Delegate network debugging tasks to cilium-manager-agent.
        #  tags: 
        #    - cilium
        #    - network
        #    - redirect
        #  examples:
        #    - "Check Cilium connectivity for namespace Y."
        #    - "Retrieve network policies applied to pod Z."
    tools:
      - type: Agent
        agent:
          apiGroup: kagent.dev
          kind: Agent
          name: k8s-agent
      #- type: Agent
      #  agent:
      #    apiGroup: kagent.dev
      #    kind: Agent
      #    name: cilium-manager-agent
