apiVersion: v1
stringData:
  GITHUB_PERSONAL_ACCESS_TOKEN: $GITHUB_PERSONAL_ACCESS_TOKEN
kind: Secret
metadata:
  name: github-mcp-secret
  namespace: kagent
type: Opaque
---
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-mcp-server
  namespace: kagent
spec:
  deployment:    
    args:
    - 'github-mcp-server --toolsets pull_requests'
    env:
      - name: GITHUB_PERSONAL_ACCESS_TOKEN
        valueFrom:
          secretRefs: 
            name: github-mcp-secret
      - name: GITHUB_TOOLSETS
        value: "repos,issues,pull_requests,actions,code_security,experiments"
    image: ghcr.io/github/github-mcp-server
    port: 3000
  transportType: stdio
