apiVersion: v1
items:
- apiVersion: kagent.dev/v1alpha2
  kind: ModelConfig
  metadata:
    name: ng-model-config
    namespace: kagent
  spec:
    apiKeySecret: kagent-openai
    apiKeySecretKey: OPENAI_API_KEY
    model: gpt-5-mini
    provider: OpenAI
kind: List