---
apiVersion: v1
kind: Endpoints
metadata:
  name: ollama
  namespace: ollama-apps
subsets:
  - addresses:
      - ip: 192.168.12.118
    ports:
      - port: 11434
        name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama-apps
spec:
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
  clusterIP: None
